media: "src/media"
content:
  - name: posts
    label: Posts
    path: content/posts
    type: collection
    filename: '{year}-{month}-{day}T{hour}:{minute}:00Z-{primary}.md'
    format: toml-frontmatter
    fields:
      - name: title
        type: string
        label: Title
        options:
          minlength: 3
          maxlength: 160
      - name: draft
        label: draft
        type: boolean
        default: false
      - name: body
        type: rich-text
        label: Body
  - name: notes
    label: notes
    path: content/notes
    type: collection
    filename: '{year}/{year}-{month}-{day}T{hour}:{minute}:00Z-{primary}.md'
    format: toml-frontmatter
    primary: body
    fields:
      - name: body
        type: rich-text
        label: Body
  - name: replies
    label: replies
    path: content/replies
    type: collection
    filename: '{year}/{year}-{month}-{day}T{hour}:{minute}:00Z-{primary}.md'
    format: toml-frontmatter
    primary: body
    fields:
      - name: in-reply-to
        type: string
      - name: body
        type: rich-text
        label: Body