[templates]
[templates.note]
input_fields = [
    {name = "contents"},
]
path = "content/notes/{{ now() | date(format=\"%Y/%Y%m%d%H%M%S\")}}/index.md"
body = """
+++
date = "{{ now() | date(format=\"%Y-%m-%dT%H:%M:%SZ\")}}"
+++

{{contents}}
"""

[templates.reply]
input_fields = [
    {name = "contents"},
    {name = "in_reply_to"},
]
path = "content/replies/{{ now() | date(format=\"%Y/%Y%m%d%H%M%S\")}}/index.md"
body = """
+++
date = "{{ now() | date(format=\"%Y-%m-%dT%H:%M:%SZ\")}}"
[extra]
in_reply_to = "{{in_reply_to}}"
+++

{{contents}}
"""

[templates.like]
input_fields = [
    {name = "contents"},
    {name = "in_like_of"},
]
path = "content/likes/{{ now() | date(format=\"%Y/%Y%m%d%H%M%S\")}}/index.md"
body = """
+++
date = "{{ now() | date(format=\"%Y-%m-%dT%H:%M:%SZ\")}}"
[extra]
in_like_of = "{{in_like_of}}"
+++

{{contents}}
"""
